[package]
name = "soyo"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23.1"
ab_glyph = "0.2.20"
raito = { path = "../raito" }

[lib]
name = "soyo"
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"
